package book.discount
import com.learn.learndrools.drools.entity.Order

//所购图书总价在100元以下的没有优惠
rule "book_discount_1"
    when
        $order:Order(originalPrice < 100) //模式匹配，到规则引擎中(工作内存) 查找Order对象
    then
        $order.setRealPrice($order.getOriginalPrice());
        System.out.println("规则一： 所购图书总价在100元以下的没有优惠");
end

//所购图书总价在100~200之间，优惠20
rule "book_discount_2"
    when
        $order: Order(originalPrice >= 100 && originalPrice < 200) //模式匹配，到规则引擎中(工作内存) 查找Order对象
    then
        $order.setRealPrice($order.getOriginalPrice() -20);
        System.out.println("规则二： 所购图书总价在100~200之间，优惠20");
end

//所购图书总价在200~300之间，优惠50
rule "book_dicscount_3"
    when
        $order: Order(originalPrice >=200 && originalPrice <300)
    then
        $order.setRealPrice($order.getOriginalPrice()-50);
        System.out.println("规则三：所购图书总价在100~200之间，优惠50");
end

//所购图书总价大于300，优惠100
rule "book_discount_4"
    when
        $order: Order(originalPrice >= 300)
    then
        $order.setRealPrice($order.getOriginalPrice()-100);
        System.out.println("规则四：所购图书总价大于300，优惠100");
end
