package testrhs
import com.learn.learndrools.drools.entity.Student
import org.drools.core.WorkingMemory

//lhs规则: in使用
rule "rhs_halt_1"
    when
    then
        System.out.println("规则rhs触发了： rhs_halt_1的使用方法");
        WorkingMemory workingMemory = drools.getWorkingMemory();
        System.out.println(workingMemory);
        org.drools.core.definitions.rule.impl.RuleImpl rule = drools.getRule();
        System.out.println(rule.getName());
        System.out.println(rule.getId());
        drools.halt();
end

rule "rhs_halt_2"
    when
    then
        System.out.println("规则rhs触发了： rhs_halt_2的使用方法");
end


